### ISSUE TITLE
Passing credentials from login form to Connection in configureStore

### ISSUE THREAD

**Issue by mstumberger** [brycedarling/redux-autobahn-js#7]
Hello,
I'm using  you'r poloniex-ticker as base for my project.

What would be the correct way to pass credentials from login form to configureStore's Connection ?
Also I need to pass some extra values to Connection and it should look like this in my case:

```
  const user = 'testuser';
  // const user = localStorage.getItem('username');
  const key = 'adminadmin';
  // const key = localStorage.getItem('key');
  const connection = new Connection({
    url: `${document.location.protocol === 'http:' ? 'ws:' : 'wss:'}//${document.location.host.split(':')[0]}:8282/ws`,
    realm: 'realm1',
    authmethods: ['wampcra'],
    authid: user,
    onchallenge: (session, method, extra) => {
      if (method === 'wampcra') {
        console.log(`authenticating via '${method}' and challenge '${extra.challenge}'`);
        return autobahn.auth_cra.sign(key, extra.challenge);
      }
      throw `don't know how to authenticate using '${method}'`;
    },
  });
```

I tried to use local storage but didn't got expected result since I had to refresh my page after login.
Also I would like to display response from server if user does not exist.
Any ideas ?

Regards, Marko

**Comment by brycedarling** [comment]
If I understand correctly, it seems like with your use case you cannot create a `Connection` object when `configureStore` is called because you don't have the auth credentials from logging in yet?

For example, you cannot do what I am doing here:
https://github.com/brycedarling/poloniex-ticker/blob/master/src/configureStore.js#L9-L12

Since the middleware requires a connection at creation, auth with user/password input can't be inserted after initialization. You aren't the first person to hit this issue and need this functionality, if you take a look at this issue you'll see someone else came up with a clever hack already (but unfortunately didn't submit a PR with their fix - maybe we could ask them to):
https://github.com/brycedarling/redux-autobahn-js/issues/2

If you can, try implementing their solution and if you get stuck let me know and I can try implement it myself. I don't have much free time right now with my current gig so hopefully you can figure it out ;) good luck!

**Comment by brycedarling** [comment]
Merged @nijuyr changes in so you can give them a shot. Please let me know if it works out for you! *fingers crossed*

**Comment by mstumberger** [comment]
Thank you @brycedarling and @nijuyr, works like a charm.

**Comment by brycedarling** [comment]
Awww yeah, really glad you got it goin, and thanks again @nijuyr you're awesome! :)
